services:
  # Kechita Intelligence Platform Web Service
  - type: web
    name: kechita-platform
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kechita-db
          property: connectionString
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/health

databases:
  # PostgreSQL Database
  - name: kechita-db
    plan: starter
    databaseName: kechita_production
    user: kechita_user
    region: oregon
